# Generated by Django 4.2.5 on 2024-04-23 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employees_visitorslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorslog',
            name='clock_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorslog',
            name='clock_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorslog',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='qrcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tag', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('availability', models.BooleanField(default=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.visitorslog')),
            ],
        ),
    ]
