# Generated by Django 4.2.5 on 2024-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_visitorslog_is_resheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorslog',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitorslog',
            name='visitation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
