# Generated by Django 4.2.5 on 2024-04-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_employees_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='usage_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
