# Generated by Django 4.2.5 on 2024-04-29 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_qrcodes_usage_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorslog',
            name='clock_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorslog',
            name='clock_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorslog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
