# Generated by Django 4.2.5 on 2024-04-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_visitorslog_clock_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='visitorslog',
            name='ref',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitorslog',
            name='status',
            field=models.CharField(blank=True, default='awaiting_confirmation', max_length=100),
        ),
    ]
