# Generated by Django 4.2.5 on 2024-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_image_alter_visitorslog_ref_alter_visitorslog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='extradetails',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
