# Generated by Django 4.2.5 on 2023-09-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadedimage_jobs_last_seen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
